# Generated by Django 5.1.1 on 2024-11-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('APART1', 'APART SIMPLE 1'), ('APART2', 'APART SIMPLE 2'), ('APART3', 'APART SIMPLE 3'), ('APART P', 'APART PREMIUM'), ('APART E', 'APART INCLUSIVO'), ('CASA1', 'CASA 1'), ('CASA2', 'CASA 2'), ('CASAGRANDE', 'CASA PARA 10 PERSONAS'), ('HOSTAL', 'HOSTAL'), ('HOSTEL', 'HOSTEL')], max_length=10),
        ),
    ]
