# Generated by Django 5.1.1 on 2024-11-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_room_description_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
