# Generated by Django 5.1.1 on 2024-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='imagen',
            field=models.ImageField(blank='True', null='True', upload_to='static/images'),
            preserve_default='True',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
