# Generated by Django 5.1.1 on 2024-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_room_imagen_delete_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='imagen',
            field=models.ImageField(blank='True', null='True', upload_to='images/'),
        ),
    ]
