# Generated by Django 5.1.1 on 2024-11-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_room_imagen_roomimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='imagen',
            new_name='image',
        ),
    ]
