# Generated by Django 5.1.1 on 2024-12-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_room_cochera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('APART1', 'APART SIMPLE 1'), ('APART2', 'APART SIMPLE 2'), ('APART3', 'APART SIMPLE 3'), ('APART4', 'APART SIMPLE 4'), ('APART5', 'APART SIMPLE 5'), ('APART P', 'APART PREMIUM'), ('APART P2', 'APART PREMIUM 2'), ('APART E', 'APART INCLUSIVO'), ('CASA1', 'CASA 1'), ('CASA2', 'CASA 2'), ('CASA3', 'CASA 3'), ('CASA4', 'CASA 4'), ('HOSTEL', 'HOSTEL')], max_length=10),
        ),
    ]
